[workspace]
members = [
    "crates/durable-streams-client",
    "crates/durable-streams-server",
]
default-members = [
    "crates/durable-streams-client",
    "crates/durable-streams-server",
]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
dbg_macro = "warn"
todo = "warn"
unwrap_used = "warn"

[workspace.metadata.durable-streams]
protocol_document = "https://github.com/durable-streams/durable-streams/blob/main/PROTOCOL.md"
protocol_revision = "8e3ef080ec3a74745ce363d59322f1cbe6de19cc"
protocol_version = "1.0-draft"
client_conformance_package = "@durable-streams/client-conformance-tests"
client_conformance_version = "0.2.3"
server_conformance_package = "@durable-streams/server-conformance-tests"
server_conformance_version = "0.3.0"
